title: TermProjectMilanLadhani
description: Term Project
template:
  repo: termprojectmilanladhani-template
  name: termprojectmilanladhani
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
